/*
? Given two integers, write a function to sum the numbers without using any arithmetic operators.
*/

#include <iostream>

using namespace std;

int sum(int a, int b)
{
    if (b == 0)
        return a;

    // a exor b (a ^ b) ==> gives current sum in binary without the carry overs
    // a and b (a & b) ==> gives the carries generated during addition
    // << 1 ==> required to adjust the carry generated by a & b
    // keep performing this till b == 0

    //    1 1     --> (a & b) << 1 [this is the carry produced, add to sum to get the final result]
    //   -------
    //    1101
    //   +0101
    //   ------
    //    1001    --> a ^ b

    return sum(a ^ b, (a & b) << 1);
}

int main()
{
    int a, b;
    cout << "Enter 1st number: ";
    cin >> a;
    cout << "Enter 2nd number: ";
    cin >> b;
    cout << "Sum (without using arithmetic operations): " << sum(a, b) << '\n';
    return 0;
}