name: Manual workflow To Get Files List Test
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Get list of files in master branch'
        default: 'Get Files List Test'
        required: true

jobs:
  get_files:
    runs-on: ubuntu-latest

    steps:
      - name: Install updates to run latest c++ binary
        run: sudo apt-get install clang --install-suggests
        
      - uses: actions/checkout@v3
      
      - name: Check clang version and path
        run: |
          which clang++
          clang++ -v
      
      - name: List files
        run: git ls-files
          
#         run: git ls-files | ./Daily_Practice
